id: P006921
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:51.510079
source_metadata:
  id: bdr:W3PD398
  title: སྒོ་བཞི་མཛོད་ལྔའི་ཡང་བཅུད།
  author: ''
  volumes:
    0698476d94584011a7da5d0414da8ec2:
      image_group_id: I4PD3254
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
    3d3433f8c92a4a26b932af4b4577406a:
      image_group_id: I4PD3255
      title: ''
      volume_number: 2
      total_pages: 264
      base_file: v002.txt
    1dd1ef49ab584bd7ac0b93d413bdfcd0:
      image_group_id: I4PD3256
      title: ''
      volume_number: 3
      total_pages: 128
      base_file: v003.txt
    2d40626f9d194bbfac3752d82ca03dac:
      image_group_id: I4PD3257
      title: ''
      volume_number: 4
      total_pages: 168
      base_file: v004.txt
    fcee792b78de41a1badae8f5b755f552:
      image_group_id: I4PD3258
      title: ''
      volume_number: 5
      total_pages: 168
      base_file: v005.txt
    9ac566f0082a44c0978e3584749d1cdd:
      image_group_id: I4PD3259
      title: ''
      volume_number: 6
      total_pages: 220
      base_file: v006.txt
    5bde3f5ae1d54acc8f1c19eafd1dfe4d:
      image_group_id: I4PD3260
      title: ''
      volume_number: 7
      total_pages: 164
      base_file: v007.txt
    c61b9ff4ed76457faf2b5f91a1d719be:
      image_group_id: I4PD3261
      title: ''
      volume_number: 8
      total_pages: 286
      base_file: v008.txt
    1545ee38cd0e467ebd1e0510d671e12e:
      image_group_id: I4PD3262
      title: ''
      volume_number: 9
      total_pages: 420
      base_file: v009.txt
    0c9ebb390b824075a1ec7fd87a3c211f:
      image_group_id: I4PD3263
      title: ''
      volume_number: 10
      total_pages: 304
      base_file: v010.txt
    be4edd4e45cf4e13831b801b929a6624:
      image_group_id: I4PD3264
      title: ''
      volume_number: 11
      total_pages: 224
      base_file: v011.txt
    f8cdbe398ee54efc98cf81eefe51da20:
      image_group_id: I4PD3265
      title: ''
      volume_number: 12
      total_pages: 456
      base_file: v012.txt
    1c6a0d8374e94417a839ef79c616d80c:
      image_group_id: I4PD3266
      title: ''
      volume_number: 13
      total_pages: 224
      base_file: v013.txt
    d1642d261940417a88813e003a74b0b7:
      image_group_id: I4PD3267
      title: ''
      volume_number: 14
      total_pages: 228
      base_file: v014.txt
    34d95b8f2fca4e8eb29ad413ac80354b:
      image_group_id: I4PD3268
      title: ''
      volume_number: 15
      total_pages: 340
      base_file: v015.txt
    36dd2e7af69646d1bba50b08055da43d:
      image_group_id: I4PD3269
      title: ''
      volume_number: 16
      total_pages: 504
      base_file: v016.txt
    851bc4e266ec4e019778e353ab1b6d13:
      image_group_id: I4PD3270
      title: ''
      volume_number: 17
      total_pages: 396
      base_file: v017.txt
    d414b442f47f40878588c95c959abf79:
      image_group_id: I4PD3271
      title: ''
      volume_number: 18
      total_pages: 408
      base_file: v018.txt
    afd2217788844df8886744318382c06a:
      image_group_id: I4PD3272
      title: ''
      volume_number: 19
      total_pages: 226
      base_file: v019.txt
    74bd6ce8774946b39f91c77ac3ced3e0:
      image_group_id: I4PD3273
      title: ''
      volume_number: 20
      total_pages: 256
      base_file: v020.txt
    cc4a6b77496542f7b284813069d85e89:
      image_group_id: I4PD3274
      title: ''
      volume_number: 21
      total_pages: 212
      base_file: v021.txt
    19d70dfd98114b478719e92e097aee70:
      image_group_id: I4PD3275
      title: ''
      volume_number: 22
      total_pages: 336
      base_file: v022.txt
    6a5f97d740b046aabaddfa4cb4dd3e8f:
      image_group_id: I4PD3276
      title: ''
      volume_number: 23
      total_pages: 312
      base_file: v023.txt
    af5c6c9d739a41b4bef5a9fd21b1fad7:
      image_group_id: I4PD3277
      title: ''
      volume_number: 24
      total_pages: 372
      base_file: v024.txt
    6d3b1c0dcdf8477997c40cee944b1d74:
      image_group_id: I4PD3278
      title: ''
      volume_number: 25
      total_pages: 336
      base_file: v025.txt
    6b3a367668e944adaab85c075afd3a8c:
      image_group_id: I4PD3279
      title: ''
      volume_number: 26
      total_pages: 312
      base_file: v026.txt
    9323c6148939401cb799314348372c6f:
      image_group_id: I4PD3280
      title: ''
      volume_number: 27
      total_pages: 220
      base_file: v027.txt
    b8cf4f16f80a4a56aa5a222a8e1517c0:
      image_group_id: I4PD3281
      title: ''
      volume_number: 28
      total_pages: 470
      base_file: v028.txt
    ea910534b8324422b158d1c22144725a:
      image_group_id: I4PD3282
      title: ''
      volume_number: 29
      total_pages: 320
      base_file: v029.txt
    d9b1bd9b3c994da7aa1e8cf990e1aeb1:
      image_group_id: I4PD3283
      title: ''
      volume_number: 30
      total_pages: 416
      base_file: v030.txt
    90a05985e8c04bde8ac833ae89d6ac56:
      image_group_id: I4PD3284
      title: ''
      volume_number: 31
      total_pages: 396
      base_file: v031.txt
    a9ace59b151a45b9b9b8b25e9f44a843:
      image_group_id: I4PD3285
      title: ''
      volume_number: 32
      total_pages: 136
      base_file: v032.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
