id: I84014494
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:15:01+00:00'
last_modified: '2022-06-08T12:29:06.707557+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD398
  title: སྒོ་བཞི་མཛོད་ལྔའི་ཡང་བཅུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9EC6:
      image_group_id: I4PD3254
      title: ''
      total_pages: 324
      order: 1
      base_file: 9EC6.txt
    DA07:
      image_group_id: I4PD3255
      title: ''
      total_pages: 264
      order: 2
      base_file: DA07.txt
    850E:
      image_group_id: I4PD3256
      title: ''
      total_pages: 128
      order: 3
      base_file: 850E.txt
    '1688':
      image_group_id: I4PD3257
      title: ''
      total_pages: 168
      order: 4
      base_file: 1688.txt
    BB78:
      image_group_id: I4PD3258
      title: ''
      total_pages: 168
      order: 5
      base_file: BB78.txt
    FE47:
      image_group_id: I4PD3259
      title: ''
      total_pages: 220
      order: 6
      base_file: FE47.txt
    5A35:
      image_group_id: I4PD3260
      title: ''
      total_pages: 164
      order: 7
      base_file: 5A35.txt
    D91B:
      image_group_id: I4PD3261
      title: ''
      total_pages: 286
      order: 8
      base_file: D91B.txt
    36A4:
      image_group_id: I4PD3262
      title: ''
      total_pages: 420
      order: 9
      base_file: 36A4.txt
    38D0:
      image_group_id: I4PD3263
      title: ''
      total_pages: 304
      order: 10
      base_file: 38D0.txt
    '8178':
      image_group_id: I4PD3264
      title: ''
      total_pages: 224
      order: 11
      base_file: 8178.txt
    DE01:
      image_group_id: I4PD3265
      title: ''
      total_pages: 456
      order: 12
      base_file: DE01.txt
    C624:
      image_group_id: I4PD3266
      title: ''
      total_pages: 224
      order: 13
      base_file: C624.txt
    '9675':
      image_group_id: I4PD3267
      title: ''
      total_pages: 228
      order: 14
      base_file: 9675.txt
    D644:
      image_group_id: I4PD3268
      title: ''
      total_pages: 340
      order: 15
      base_file: D644.txt
    DC48:
      image_group_id: I4PD3269
      title: ''
      total_pages: 504
      order: 16
      base_file: DC48.txt
    A0C5:
      image_group_id: I4PD3270
      title: ''
      total_pages: 396
      order: 17
      base_file: A0C5.txt
    6CEE:
      image_group_id: I4PD3271
      title: ''
      total_pages: 408
      order: 18
      base_file: 6CEE.txt
    '4089':
      image_group_id: I4PD3272
      title: ''
      total_pages: 226
      order: 19
      base_file: 4089.txt
    5E8D:
      image_group_id: I4PD3273
      title: ''
      total_pages: 256
      order: 20
      base_file: 5E8D.txt
    FFF4:
      image_group_id: I4PD3274
      title: ''
      total_pages: 212
      order: 21
      base_file: FFF4.txt
    7C6D:
      image_group_id: I4PD3275
      title: ''
      total_pages: 336
      order: 22
      base_file: 7C6D.txt
    F9FA:
      image_group_id: I4PD3276
      title: ''
      total_pages: 312
      order: 23
      base_file: F9FA.txt
    DB91:
      image_group_id: I4PD3277
      title: ''
      total_pages: 372
      order: 24
      base_file: DB91.txt
    1D67:
      image_group_id: I4PD3278
      title: ''
      total_pages: 336
      order: 25
      base_file: 1D67.txt
    B71E:
      image_group_id: I4PD3279
      title: ''
      total_pages: 312
      order: 26
      base_file: B71E.txt
    9ABA:
      image_group_id: I4PD3280
      title: ''
      total_pages: 220
      order: 27
      base_file: 9ABA.txt
    '7453':
      image_group_id: I4PD3281
      title: ''
      total_pages: 470
      order: 28
      base_file: 7453.txt
    10FB:
      image_group_id: I4PD3282
      title: ''
      total_pages: 320
      order: 29
      base_file: 10FB.txt
    0EDE:
      image_group_id: I4PD3283
      title: ''
      total_pages: 416
      order: 30
      base_file: 0EDE.txt
    '1394':
      image_group_id: I4PD3284
      title: ''
      total_pages: 396
      order: 31
      base_file: 1394.txt
    29D7:
      image_group_id: I4PD3285
      title: ''
      total_pages: 136
      order: 32
      base_file: 29D7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
